export const SAVE_SIGNIN_FORM = "SAVE_SIGNIN_FORM";
export const SAVE_SIGNUP_FORM = "SAVE_SIGNUP_FORM";
export const SAVE_AUTHENTICATED_USER = "SAVE_AUTHENTICATED_USER";
export const SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED";
export const CHECK_IS_AUTHENTICATED = "CHECK_IS_AUTHENTICATED";
